name: Docs

on:
  push:
    branches:
      - "main"

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    strategy:
      matrix:
        composer-command:
          - name: Generate docs
            command: 'docs:generate'
        directory: ['typo3-fractor', 'fractor-composer-json']

    name: '${{ matrix.composer-command.name }}/packages/${{ matrix.directory }}'

    defaults:
      run:
        working-directory: packages/${{ matrix.directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install composer dependencies
        uses: php-actions/composer@v6
        with:
          container_workdir: /app/packages/${{ matrix.directory }}
          memory_limit: 512M

      - name: 'Run check "${{ matrix.composer-command.name }}"'
        uses: php-actions/composer@v6
        with:
          container_workdir: /app/packages/${{ matrix.directory }}
          command: ${{ matrix.composer-command.command }}
          memory_limit: 512M
      - name: 'Set Branch Name'
        id: set-branch-name
        run: |
            branch_name="dynamic-branch-$(date +'%Y%m%d%H%M%S')"
            echo "::set-output name=branch_name::$branch_name"
      - name: "Commit documentation"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '*.md'
          disable_globbing: true
          commit_message: '[DOCS] Generate documentation'
          commit_options: '--no-verify --signoff'
          create_branch: true
          branch: "feature-create-docs-${{ steps.set-branch-name.outputs.branch_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create Pull Request"
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "feature-create-docs-${{ steps.set-branch-name.outputs.branch_name }}"
