name: publish
on:
  push:
    branches:
      - main
    tags:
      - v**

jobs:
  subtree-split:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - path: extension-installer
            repository: git@github.com:andreaswolf/fractor-extension-installer.git
            deploy-key: DEPLOY_KEY_EXTENSION_INSTALLER
          - path: fractor
            repository: git@github.com:andreaswolf/fractor-fractor.git
            deploy-key: DEPLOY_KEY_FRACTOR
          - path: typo3-fractor
            repository: git@github.com:andreaswolf/fractor-typo3-fractor.git
            deploy-key: DEPLOY_KEY_TYPO3_FRACTOR
          - path: fractor-xml
            repository: git@github.com:andreaswolf/fractor-xml.git
            deploy-key: DEPLOY_KEY_XML_FRACTOR

    name: Split subtree ${{ matrix.package.path }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # ensure the complete Git history is available

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets[matrix.package.deploy-key] }}

      - name: Split and push
        run: |
          SPLIT_REF=$(git subtree -P ${{ matrix.package.path }} split)
          
          git push ${{ matrix.package.repository }} $SPLIT_REF:${{ github.event.ref }} -f
